name = "TypeSerializers"
uuid = "66ceb7d2-8c8e-4075-97ca-ace8f0b9e750"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.1.0"

[compat]
julia = "1"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
